version: "3"

services:
  postgres:
    image: "postgres:alpine"
    container_name: "postgres"
    restart: "always"
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
